name: Tag

on:
  push:
    tags: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_noble:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Install Rust
      run: rustup component add rustfmt clippy

    - name: Install other dependencies
      run: sudo apt-get -qqy install build-essential libclang-dev

    - name: Publish Dry-Run
      run: |
        cargo publish --dry-run -p bindex
